version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prodvor
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: E:/prodvor_data/postgres
        target: /var/lib/postgresql/data
    networks:
      - prodvor-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on: [postgres]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - type: bind
        source: E:/prodvor_data/pgadmin
        target: /var/lib/pgadmin
    networks: [prodvor-network]

networks:
  prodvor-network:
    driver: bridge
